name: common_services
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_localizations:
    sdk: flutter
  ## CORE MODULES
  core:
    path: ../../core
  design_system:
    path: ../../../design_system

  ## EXTERNAL PACKAGES
  dartz: ^0.10.1
  flutter_riverpod: ^2.3.4
  go_router: ^12.0.1
  
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.0.1
  json_annotation: ^4.8.0
  mocktail: ^0.3.0
  matcher: ^0.12.15
  mobile_scanner: ^3.5.1
  flutter_screenutil: ^5.8.4
  webview_flutter: ^4.8.0

dependency_overrides:
  webview_flutter_android: 3.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      # This plugin project was generated without specifying any
      # platforms with the `--platform` argument. If you see the `some_platform` map below, remove it and
      # then add platforms following the instruction here:
      # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
      # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------
