include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    - annotate_overrides
    - await_only_futures
    - camel_case_types
    - empty_constructor_bodies
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_unused_constructor_parameters
    - file_names
    - non_constant_identifier_names
    - one_member_abstracts
    - prefer_conditional_assignment
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_typing_uninitialized_variables
    - sort_constructors_first
    - unawaited_futures
    - always_declare_return_types
    - avoid_empty_else
    - unnecessary_new
    - valid_regexps
    - avoid_multiple_declarations_per_line
    - empty_catches
    - avoid_print
    - test_types_in_equals
    - unnecessary_overrides
    - avoid_redundant_argument_values
    - use_key_in_widget_constructors
    - unnecessary_this
    - prefer_contains
    - prefer_is_not_empty