name: auth
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_localizations:
    sdk: flutter
  ## CORE MODULES
  core:
    path: ../../core

  common_services:
    path: ../common_services
  address:
    path: ../address



  ## EXTERNAL PACKAGES
  dartz: ^0.10.1
  flutter_riverpod: ^2.3.4
  go_router: ^12.0.1
  
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  formz: ^0.6.0
  riverpod_annotation: ^2.0.1
  google_sign_in: ^6.1.0
  mocktail: ^0.3.0
  firebase_core: ^2.10.0
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.3
  equatable: ^2.0.5
  matcher: ^0.12.15
  dart_jsonwebtoken: ^2.8.2
  lottie: ^3.1.2
  flutter_screenutil: ^5.8.4
  copy_with_extension_gen: ^5.0.3
  el_tooltip: 2.0.0

dependency_overrides:
  webview_flutter_android: 3.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
      # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------

targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.fr.dart
