name: profile
description: A new Flutter plugin project.
version: 0.0.1
homepage:
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  ## CORE MODULES
  core:
    path: ../../core
  design_system:
    path: ../../../design_system
  map:
    path: ../map
  common_services:
    path: ../common_services
  address:
    path: ../address


  auth:
    path: ../auth

  ## EXTERNAL PACKAGES
  dartz: ^0.10.1
  flutter_riverpod: ^2.3.4
  go_router: ^12.0.1
  
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.0.1
  json_annotation: ^4.8.1
  mocktail: ^0.3.0
  cached_network_image: ^3.2.3
  auto_size_text: ^3.0.0
  mockito: ^5.4.1
  equatable: ^2.0.5
  flutter_svg: ^2.0.6
  animations: ^2.0.7
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.0
  awesome_snackbar_content: ^0.1.3
  flutter_screenutil: ^5.8.4
  dropdown_search: ^5.0.6
  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.4
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.fr.dart

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      # This plugin project was generated without specifying any
      # platforms with the `--platform` argument. If you see the `some_platform` map below, remove it and
      # then add platforms following the instruction here:
      # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
      # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------
