name: super99
description: App ecommerce super99.
publish_to: "none"

version: 1.0.5+3

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  ## CORE MODULES
  core:
    path: core
  ## FEATURES MODULES
  auth:
    path: feature/auth
  store:
    path: feature/store
  map:
    path: feature/map
  profile:
    path: feature/profile
  common_services:
    path: feature/common_services
  address:
    path: feature/address


  ## EXTERNAL PACKAGES
  dartz: ^0.10.1
  rxdart: ^0.28.0
  go_router: ^12.0.1
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  firebase_core: ^2.10.0
  google_maps_flutter: ^2.2.6
  firebase_messaging: ^14.6.2
  flutter_screenutil: ^5.8.4
  dropdown_search: ^5.0.6
  logger: ^1.3.0
  firebase_crashlytics: ^3.4.18
  graphql: ^5.2.0-beta.11
  advertising_id: ^2.7.1

dependency_overrides:
  webview_flutter_android: 3.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.3
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16
  melos: ^6.3.2

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: packages/design_system/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: packages/design_system/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: packages/design_system/fonts/Rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/design_system/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: packages/design_system/fonts/Rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: packages/design_system/fonts/Rubik/Rubik-Italic.ttf
          style: italic
        - asset: packages/design_system/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: packages/design_system/fonts/Rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/design_system/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: packages/design_system/fonts/Rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/design_system/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: packages/design_system/fonts/Rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Gotham
      fonts:
        - asset: packages/design_system/fonts/Gotham/Gotham-Bold.otf
          weight: 700
        - asset: packages/design_system/fonts/Gotham/Gotham-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/design_system/fonts/Gotham/Gotham-Book.ttf
          weight: 400
        - asset: packages/design_system/fonts/Gotham/Gotham-BookItalic.ttf
          weight: 400
          style: italic
        - asset: packages/design_system/fonts/Gotham/Gotham-Light.otf
          weight: 300
        - asset: packages/design_system/fonts/Gotham/Gotham-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/design_system/fonts/Gotham/Gotham-Medium.ttf
          weight: 500
        - asset: packages/design_system/fonts/Gotham/Gotham-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/design_system/fonts/Gotham/Gotham-Thin.otf
          weight: 100
        - asset: packages/design_system/fonts/Gotham/Gotham-ThinItalic.otf
          weight: 100
          style: italic

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.fr.dart
