// Mocks generated by Mockito 5.4.5 from annotations
// in store/test/order/domain/use_case/place_order_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:core/local/data/datasource/secure_storage_datasource.dart'
    as _i7;
import 'package:core/local/data/repository/secure_storege_repository.dart'
    as _i3;
import 'package:core/local/key_secure_storage.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:rxdart/rxdart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueStream_0<T> extends _i1.SmartFake
    implements _i2.ValueStream<T> {
  _FakeValueStream_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SecureStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageRepository extends _i1.Mock
    implements _i3.SecureStorageRepository {
  @override
  _i4.Future<void> saveData(
    _i5.KeySecureStorage? key,
    String? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveData,
          [
            key,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> getData(_i5.KeySecureStorage? key) => (super.noSuchMethod(
        Invocation.method(
          #getData,
          [key],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getData,
            [key],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getData,
            [key],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> deleteData(_i5.KeySecureStorage? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteData,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.ValueStream<_i7.EventDataSecureStorage> getStreamEventChangeData() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreamEventChangeData,
          [],
        ),
        returnValue: _FakeValueStream_0<_i7.EventDataSecureStorage>(
          this,
          Invocation.method(
            #getStreamEventChangeData,
            [],
          ),
        ),
        returnValueForMissingStub:
            _FakeValueStream_0<_i7.EventDataSecureStorage>(
          this,
          Invocation.method(
            #getStreamEventChangeData,
            [],
          ),
        ),
      ) as _i2.ValueStream<_i7.EventDataSecureStorage>);
}
