name: flutter_instaleap_sdk
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  hive: ^2.2.3
  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  equatable: ^2.0.5
  http:
  async: ^2.11.0
  flutter_secure_storage: ^9.2.4
  logger: ^1.3.0
  omni_adobe_core:
    path: ../../omnipro_ecommerce_sdk_flutter/omni_adobe_core
    #git:
      #path: omni_adobe_core
      #url: git@github.com:omni-pro/omnipro_ecommerce_sdk_flutter.git
      #ref: production

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  lints: ^5.1.1
  test: ^1.21.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  copy_with_extension_gen: ^6.0.1
  mocktail: ^0.3.0
  mockito: ^5.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages

targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.fr.dart