name: omnipro_ecommerce_sdk
description: "SDK para apps Flutter que usen Magento Cloud"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ## CORE MODULES
  core:
    path: core
  ## FEATURES MODULES
  auth:
    path: feature/auth
  store:
    path: feature/store
  map:
    path: feature/map
  profile:
    path: feature/profile
  common_services:
    path: feature/common_services

  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  logger: ^1.3.0
  graphql:
  hive: ^2.2.3
  gql_transform_link: ^1.0.0
  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  formz: ^0.6.0
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.1.0
  equatable: ^2.0.5
  url_launcher: 6.3.0
  firebase_remote_config: ^4.1.0
  permission_handler: ^10.2.0
  share_plus: ^7.0.1
  firebase_messaging: ^14.6.7
  firebase_core: ^2.10.0
  firebase_analytics: ^10.4.4
  hive_flutter: ^1.1.0
  package_info_plus: ^4.1.0
  collection: ^1.17.1
  http:
  async: ^2.11.0
  synchronized: ^3.1.0+1
  connectivity_plus: ^6.0.3
  el_tooltip: 2.0.0
  flutter_udid: ^3.0.0
  html: ^0.15.5
  encrypt: ^5.0.3
  latlong2: ^0.9.1
  flutter_test:
    sdk: flutter
  firebase_database: ^10.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: omnipro.omnipro_ecommerce_sdk
        pluginClass: OmniproEcommerceSdkPlugin
      ios:
        pluginClass: OmniproEcommerceSdkPlugin

