name: omnipro_ecommerce_sdk
description: "SDK para apps Flutter que usen Magento Cloud"
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ## CORE MODULES
  core:
    path: core

  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  logger: ^1.3.0
  graphql:
  hive: ^2.2.3
  gql_transform_link: ^1.0.0
  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1
  formz: ^0.6.0
  flutter_secure_storage: ^9.2.4
  google_sign_in: ^6.1.0
  equatable: ^2.0.5
  url_launcher: 6.3.0
  firebase_remote_config: ^4.1.0
  permission_handler: ^10.2.0
  share_plus: ^7.0.1
  firebase_messaging: ^14.6.7
  firebase_core: ^2.10.0
  firebase_analytics: ^10.4.4
  hive_flutter: ^1.1.0
  package_info_plus: ^4.1.0
  collection: ^1.17.1
  http:
  async: ^2.11.0
  synchronized: ^3.1.0+1
  connectivity_plus: ^6.0.3
  el_tooltip: 2.0.0
  flutter_udid: ^3.0.0
  html: ^0.15.5
  encrypt: ^5.0.3
  latlong2: ^0.9.1
  dart_jsonwebtoken: ^2.8.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_google_places_sdk: 0.3.8
  sign_in_with_apple: ^6.1.4
  go_router: ^14.8.0
  rxdart: ^0.28.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  lints: ^5.1.1
  test: ^1.21.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  copy_with_extension_gen: ^6.0.1
  mocktail: ^0.3.0
  mockito: ^5.4.1

flutter:
  plugin:
    platforms:
      android:
        package: omnipro.omnipro_ecommerce_sdk
        pluginClass: OmniproEcommerceSdkPlugin
      ios:
        pluginClass: OmniproEcommerceSdkPlugin


targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:freezed:
        generate_for:
          include:
            - lib/**.fr.dart

