name: core
publish_to: "none"
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.27.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  omnipro_ecommerce_sdk:
    path: ../


dev_dependencies:
  freezed: ^2.5.8
  build_runner: ^2.4.15
  lints: ^5.1.1
  test: ^1.21.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.6.4
  mocktail: ^0.3.0

dependency_overrides:
  webview_flutter_android: 3.16.1

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:freezed:
        generate_for:
          include:
            - lib/**.fr.dart
